"""add is_active field to vehicles

Revision ID: 2dfd1e7d96c2
Revises: 6afdc12ad3c0
Create Date: 2025-10-07 12:07:31.679757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfd1e7d96c2'
down_revision: Union[str, Sequence[str], None] = '6afdc12ad3c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_annual_current_result', 'annual_inspections', 'inspection_results', ['current_result_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL', use_alter=True)
    op.add_column('vehicles', sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_active')
    op.drop_constraint('fk_annual_current_result', 'annual_inspections', type_='foreignkey')
    # ### end Alembic commands ###
